schema_version: 1

context:
  name: arviz-stats
  version: "0.6.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/arviz_stats-${{ version }}.tar.gz
  sha256: 0a85f7c062aeeae35afc0e7a21bb00d0557a3b9704193e5307a4298270ebadfb

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.4,<4
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2
    - scipy >=1.10
    - arviz-base ==0.6.0
    - xarray-einstats
    - numba

tests:
  - python:
      imports:
        - arviz_stats
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*

about:
  summary: Statistical computation and diagnostics for ArviZ.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/arviz-devs/arviz-stats
  repository: https://github.com/arviz-devs/arviz-stats
  documentation: https://arviz-stats.readthedocs.io

extra:
  recipe-maintainers:
    - OriolAbril
    - aloctavodia
    - tomicapretto
